function pdemodel
[pde_fig,ax]=pdeinit;
pdetool('appl_cb',1);
set(ax,'DataAspectRatio',[1 1 1]);
set(ax,'PlotBoxAspectRatio',[4 4 1]);
set(ax,'XLim',[-4 4]);
set(ax,'YLim',[-4 4]);
set(ax,'XTickMode','auto');
set(ax,'YTickMode','auto');

% Geometry description:
pdeellip(0,0,4,4,...
0,'E2');
set(findobj(get(pde_fig,'Children'),'Tag','PDEEval'),'String','E2')

% Boundary conditions:
pdetool('changemode',0)
pdesetbd(4,...
'dir',...
1,...
'1',...
'.1')
pdesetbd(3,...
'dir',...
1,...
'1',...
'.1')
pdesetbd(2,...
'dir',...
1,...
'1',...
'.1')
pdesetbd(1,...
'dir',...
1,...
'1',...
'.1')

% Mesh generation:
setappdata(pde_fig,'Hgrad',1.3);
setappdata(pde_fig,'refinemethod','regular');
setappdata(pde_fig,'jiggle',char('on','mean',''));
setappdata(pde_fig,'MesherVersion','preR2013a');
pdetool('initmesh')

% PDE coefficients:
pdeseteq(1,...
char('-.5','0','0','0'),...
'2*(1-2*x)',...
'(-x+(x.^2-y.^2)).*ux+(-y+2.*x.*y).*uy',...
'1.0',...
'0:10',...
'0.0',...
'0.0',...
'[0 100]')
setappdata(pde_fig,'currparam',...
['-.5 0 0 0                            ';...
'2*(1-2*x)                            ';...
'(-x+(x.^2-y.^2)).*ux+(-y+2.*x.*y).*uy';...
'1.0                                  '])

% Solve parameters:
setappdata(pde_fig,'solveparam',...
char('1','11843','10','pdeadworst',...
'0.2','longest','1','1e-5','1','full','inf'))

% Plotflags and user data strings:
setappdata(pde_fig,'plotflags',[1 1 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 1]);
setappdata(pde_fig,'colstring','');
setappdata(pde_fig,'arrowstring','');
setappdata(pde_fig,'deformstring','');
setappdata(pde_fig,'heightstring','');

% Solve PDE:
pdetool('solve')
